services:
  - type: web
    name: millow-server
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: PORT
        value: 4000
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false # This will need to be set in Render's dashboard
      - key: OPENAI_API_KEY
        sync: false # This will need to be set in Render's dashboard
    routes:
      - type: rewrite
        source: /*
        destination: / 